### ISSUE TITLE
automatische Pfadgenerierung anpassen

### ISSUE THREAD

**Issue by Idontker** [Idontker/AlgoKueche#32]
Pfadgenerierung geht schief, wenn man das oberste package src entfernt. Generell scheint dies eine problematische Stelle, bei der nicht sicher ist, wie das Problem am besten für BlueJ und VS Code zu lösen ist.

**Comment by baletiballo** [comment]
Der build Path in VSCode scheint sich nicht ändern zu lassen. Entweder wir bleiben in BlueJ (dass erlaubt relative Pfade) oder wir nutzen eine lokale Datei bei jedem von uns, die den PfadZuAlgoKueche enthält (und nicht synchronisiert wird)

**Comment by Idontker** [comment]
Es scheint keine Lösung für beide IDEs zu geben.
