### ISSUE TITLE
Endlose Wiederholungen abfangen

### ISSUE THREAD

**Issue by Idontker** [Idontker/AlgoKueche#34]

**Comment by Idontker** [comment]
Ideen: 

- Warning-Slide
- Warning-Comment
- Exception

**Comment by Idontker** [comment]
Ideen:

- [ ] im Lehrling eine eigene goToFrame Methode erstellen, welche:
- [ ] überprüft, ob die vorgesehene Anzahl an Schritten überschritten wurde
- [ ] aktuelle Schritte um 1 erhöht 
- [ ] nach Überschreitung jeweils ein "warning" anzeigt.
- [ ] Dieses "warning" kann man  nur X-mal anzeigen lassen.

**Comment by Gebhart97** [comment]
Is done
