### ISSUE TITLE
Leerzeichen in Rezepten rauslöschen

### ISSUE THREAD

**Issue by Idontker** [Idontker/AlgoKueche#42]
- Leerzeichen entfernen 

Wahrscheinlich ist es sinnvoll das Einlesen von Rezepten und Zutaten in ein Formatiere umzuwandeln.

**Comment by baletiballo** [comment]
Sowohl der Rezeptname, als auch die Zutatennamen laufen jetzt durch Formatierung.formatiere(). Wenn ich nichts übersehen habe, könne wir das Issue schließen

**Comment by Idontker** [comment]
sieht gut aus.
