### ISSUE TITLE
Erstellung einer Formatierungsklasse

### ISSUE THREAD

**Issue by Idontker** [Idontker/AlgoKueche#43]
Das Format soll an einer Stelle aktualisiert/bearbeitet/vereinheitlicht werden.

**Comment by Idontker** [comment]
gibt auch die Möglichkeit, zutaten wieder einheitlich groß zu schreiben (mit Blick auf Ausgabe).

**Comment by baletiballo** [comment]
Die Klasse Hilfsklassen.cooking.Formatierung stellt jetzt die entsprechenden Funktionen als statische Methoden bereit. Bitte zusätzliche Zutatennamen dort einfügen.
Formatierung ist:
Keine Leerzeichen, alles klein, bis auf das erste Zeichen, das ist groß
